trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  displayName: 'Instalando .NET SDK 6.0'
  inputs:
    packageType: 'sdk'
    version: '6.0.301'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    arguments: '--configuration Release'

- task: PublishBuildArtifacts@1
  displayName: 'Publicando los artefactos'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'